feature: Support Flat configs in v8
sarbbottam/eslint-find-rules pull request #354
Opened 2024-10-04 00:13 UTC by lotmek

## Description
- Handle flat confid in `rule-finder.js`
- Add a new `--flatConfig` flag
- Load ESLint class using [loadESLint()](https://eslint.org/docs/latest/integrate/nodejs-api#loadeslint) function
- Add unit tests for basic flat config

2024-10-04 08:35 UTC, ljharb requested changes

2024-10-04 08:35 UTC, ljharb commented on src/bin/find.js
> +  useFlatConfig: semver.satisfies(eslintPkg.version, '>= 8.57') && argv.flatConfig
all this PR seems to do is prevent `useFlatConfig` from being `true` in an eslint without flat config support

2024-10-04 08:37 UTC, ljharb commented on test/lib/rule-finder.js
> +    get: function(id) {
```suggestion
    get(id) {
```

2024-10-04 10:25 UTC, lotmek commented on src/bin/find.js
> +  useFlatConfig: semver.satisfies(eslintPkg.version, '>= 8.57') && argv.flatConfig
done 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/5aa58108-fd66-4ff9-aa36-03fccebd8906">

2024-10-05 04:19 UTC, ljharb requested changes

2024-10-05 04:19 UTC, ljharb commented on src/lib/rule-finder.js
> +    throw ('This version of ESLint does not support flat config.')
```suggestion
    throw 'This version of ESLint does not support flat config.';
```

2024-10-05 04:19 UTC, ljharb commented on src/lib/rule-finder.js
> +    if(useFlatConfig) {
```suggestion
    if (useFlatConfig) {
```

2024-10-05 04:19 UTC, ljharb commented on src/lib/rule-finder.js
> +      });
```suggestion
      Object.entries(config.plugins)
        .filter(([, { rules }) => rules)
        .forEach(([pluginName, { rules }]) => {
          Object.keys(rules).forEach(ruleName =>
            pluginRules.set(`${pluginName}/${ruleName}`, rules[ruleName])
          );
        });
```

2024-10-05 04:19 UTC, ljharb commented on src/lib/rule-finder.js
> +        );
```suggestion
        if (pluginConfig.rules) {
          Object.keys(pluginConfig.rules).forEach(ruleName =>
            pluginRules.set(`${normalized.prefix}/${ruleName}`, rules[ruleName])
          );
        }
```

2024-10-05 04:19 UTC, ljharb commented on src/lib/rule-finder.js
> +  return builtinRules ? builtinRules : new Linter().getRules();
```suggestion
  return builtinRules || new Linter().getRules();
```

2024-10-06 00:58 UTC, ljharb approved these changes
LGTM, this will be semver-minor

2024-10-06 01:22 UTC, ljharb commented
@lotmek it looks like the exception is always being thrown.

2024-10-06 01:38 UTC, lotmek commented
> @lotmek it looks like the exception is always being thrown.

Hello @ljharb, tell me if I'm wrong, but I think flat configs are not supported in ESLint v7

I can add a condition to skip the flat config tests if ESLint version is lower than 8, what do you think of it ?

```js
  if (semver.satisfies(eslintPkg.version, '>= 8')) {
    describe('flat config', () => {
        ...
    })
  }
```

2024-10-06 01:44 UTC, ljharb commented
I have eslint 8.56 installed and it's still failing locally, fwiw.

Certainly the flat config tests should be ensuring it throws in eslint 7, good catch.

2024-10-06 02:26 UTC, lotmek commented
> I have eslint 8.56 installed and it's still failing locally, fwiw.
> 
> Certainly the flat config tests should be ensuring it throws in eslint 7, good catch.

I did some changes, can you try again ?

2024-10-06 06:30 UTC, ljharb commented
LGTM, thanks

2024-10-06 06:33 UTC, merged