feat: Add support for ESLint v9
sarbbottam/eslint-find-rules pull request #356
Opened 2024-10-06 16:17 UTC by lotmek

## Description
Continuing the flat config support in v9 https://github.com/sarbbottam/eslint-find-rules/issues/351
- Add support for ESLint v9 by using `LegacyESLint` class when it is defined
- Update documentation to explain v9 support
- Add ESLint v9 to Node compatibility workflow, ignoring the versions that don't match `^18.18.0 || ^20.9.0 || >=21.1.0`
- Replace `.eslintignore` by `ignorePatterns` at the root level of the project to remove warning message in the tests

2024-10-07 05:45 UTC, ljharb commented
Unfortunately this is a duplicate of #353. Please leave this PR open so I can keep both in sync (in the future, instead of opening a duplicate PR, please comment with a link to commits on the existing one, and I can pull them in)

2024-10-07 05:48 UTC, ljharb requested changes
I don't see any tests here.

Can you rebase these changes on top of #353 and ensure there's adequate passing tests?

2024-10-07 05:48 UTC, ljharb commented on README.md
> +<u>**Note:**</u> ESLint v9 support requires a recent version of Node.JS: `^18.18.0 || ^20.9.0 || >=21.1.0`, as mentionned in the [ESLint documentation](https://eslint.org/docs/latest/use/migrate-to-9
```suggestion
<u>**Note:**</u> ESLint v9 support requires a recent version of Node.JS: `^18.18.0 || ^20.9.0 || >=21.1.0`, as mentioned in the [ESLint documentation](https://eslint.org/docs/latest/use/migrate-to-9.0.0#-nodejs--v1818-v19-are-no-longer-supported).
```

2024-10-07 05:48 UTC, ljharb commented on package.json
> +    "cross-env": "^7.0.3",
unfortunately we support 10.12, and cross-env 7 requires 10.14. we can use v6 tho.
```suggestion
    "cross-env": "^6.0.3",
```

2024-10-08 11:58 UTC, lotmek commented
Hello @ljharb @yutak23,
Can you please take a look at my PR https://github.com/lotmek/eslint-find-rules/pull/1 ?
I will bring the test data for ESLint v9 and split the tests between legacy and flat config

2025-01-20 02:31 UTC, ljharb commented
I believe this is now obviated by #353.

2025-01-20 02:31 UTC, closed without merging